version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      - pip install sphinxcontrib-bibtex
      - pip install sphinxcontrib-pseudocode
      - pip install sphinx-copybutton
